config/routes.rb
Rails.application.routes.draw do
  resources :products, only: %i[index show]

  root to: 'products#index'

  devise_for :users

  namespace :admin do
    resources :products
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many_attached :pics, dependent: :destroy

  validates_presence_of :name, :price

  enum status: { on_shelves: 0, stock: 1, off_shelves: -1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: %i[show edit update destroy]

  require 'securerandom'

  def index
    @products = current_user.products.all.order(created_at: :desc)
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    random = SecureRandom.hex(2)
    @product.sku = "#{Time.current.to_i}#{random}"

    if @product.save
      respond_to :js
    else
      respond_to { |format| format.js { render js: "alert('input error')" } }
    end
  end

  def update
    if params[:status].present?
      @product.update(status: params[:status])
      redirect_to admin_products_path
    elsif @product.update(product_params)
      respond_to :js
    else
      respond_to { |format| format.js { render js: "alert('input error')" } }
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, notice: 'delete success'
  end

  private

  def product_params
    params.require(:product).permit(:name, :status, :original_price, :price, pics: [])
  end

  def find_product
    @product = current_user.products.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.where(status: :on_shelves).order(created_at: :desc)
  end

  def show
    @product = Product.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def image(product)
    default_cover = 'https://picsum.photos/200/200'

    image_tag product.pics.first || default_cover
  end
end

app/views/admin/products/_product.html.erb
<tr id="<%= product.id %>" class="text-center">
  <td><%= product.sku %></td>
  <td><%= product.name %></td>
  <td>
    <%= form_tag admin_product_path(product), method: :patch do %>
      <%= select_tag :status, options_for_select(Product.statuses.keys.to_a, product.status), class: "form-control-sm" %>
      <%= submit_tag 'Update', class: "btn btn-outline-info btn-sm" %>
    <% end %>
  </td>
  <td><%= product.updated_at.strftime("%F %T") %></td>
  <td>
    <% if user_signed_in? %>
      <%= link_to 'Show', admin_product_path(product), remote: true, class: 'btn btn-outline-secondary btn-sm' %>
      <%= link_to 'Edit', edit_admin_product_path(product), remote: true, class: 'btn btn-outline-warning btn-sm' %>
      <%= link_to 'Delete', admin_product_path(product), remote: true,
            method: 'delete', data: { confirm: "Are you sure to delete?" }, class: 'btn btn-outline-danger btn-sm' %>
    <% end %>
  </td>
</tr>

app/views/admin/products/_product_form.html.erb
<div class="modal fade" id="<%= id %>">
  <%= simple_form_for(action, url: url, remote: true) do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= title %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-inputs">
          <%= f.input :name, class: 'form-control' %>
          <%= f.input :original_price, class: 'form-control' %>
          <%= f.input :price, class: 'form-control' %>
        </div>

        <div class="field">
          <label for="product_pics">Pictures</label>
          <%= f.file_field :pics, multiple: true %>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.button :submit, 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/products/_show.html.erb
<div class="modal fade" id="show_product">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Product</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body overflow-auto">
        <div>
          <strong>Name:</strong>
          <span><%= @product.name %></span>
        </div>

        <div>
          <strong>Status:</strong>
          <span><%= @product.status %></span>
        </div>

        <div>
          <strong>Original Price:</strong>
          <span><%= @product.original_price %></span>
        </div>

        <div>
          <strong>Price:</strong>
          <span><%= @product.price %></span>
        </div>

        <div>
          <strong>Pictures:</strong>
          <div class='d-flex flex-column'>
            <% @product.pics.each do |pic| %>
              <%= image_tag pic, class: 'w-75 m-1' %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/create.js.erb
$('#products').prepend('<%= j render @product %>');
$('#new_product').modal('hide');

app/views/admin/products/edit.js.erb
$('#edit-container').html('<%= j render 'admin/products/product_form',
                                   id: 'edit_product',
                                   action: @product,
                                   url: admin_product_path(@product),
                                   title: 'Edit product' %>');
$('#edit_product').modal('show');

app/views/admin/products/index.html.erb
<div class="container">
  <h1>Products</h1>
  <%= link_to 'New product', '#new_product', data: { toggle: 'modal' }, class: 'btn btn-info m-2' %>
  <table class="table table-condensed">
    <thead>
      <tr class="text-center">
        <th>SKU</th>
        <th>Name</th>
        <th>Status</th>
        <th>Updated at</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody id='products'>
      <%= render @products %>
    </tbody>
  </table>
</div>

<%= render 'admin/products/product_form', id: 'new_product',
    action: Product.new, url: admin_products_path, title: 'New product' %>

<div id='edit-container'></div>

<div id='show-container'></div>

app/views/admin/products/update.js.erb
$('.modal').each(function(index, element) {
  $(element).modal('hide');
});

$('#<%= @product.id %>').replaceWith('<%= j render @product %>');

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"></span>
        <%= link_to 'Eslite', products_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse flex-grow-1 text-right">
      <ul class="navbar-nav ml-auto flex-nowrap">
      <%= link_to 'Admin', admin_products_path, class: 'navbar-brand' %>
      <% if current_user %>
        <span class="navbar-brand"><%= current_user.email %></span>
        <%= link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
      <% end %>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductEslite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%= stylesheet_link_tag 'products' %>

<div class="container">
	<% @products.each do |product| %>
  <div class="card mb-3 mt-3" style="max-width: 540px; margin: auto;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <div class="card-img">
	        <%= image(product) %>
	      </div>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text">
            <strong>price: </strong>
            <del><%= product.original_price %></del>
            <span class="text-success"><%= product.price %></span>
          </p>
          <a href="<%= admin_product_path(product) %>" data-remote="true" class="btn btn-info">Detail</a>
        </div>
      </div>
    </div>
  </div>
	<% end %>
</div>

<div id='show-container'></div>

app/views/products/show.js.erb
$('#show-container').html('<%= j render 'admin/products/show' %>');
$('#show_product').modal('show');